# Generated by Django 4.0.1 on 2022-10-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='times_deleted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='times_posted',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
