# Generated by Django 4.0.1 on 2022-10-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0002_alter_annonce_times_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='times_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='times_posted',
            field=models.IntegerField(default=0),
        ),
    ]
