# Generated by Django 4.2.3 on 2023-07-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number_of_ads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='time_in_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
