# Generated by Django 4.2.3 on 2023-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_number_of_ads_account_time_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last triggered'),
        ),
    ]
