# Generated by Django 4.2.3 on 2023-07-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_last_triggered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_triggered',
        ),
        migrations.AlterField(
            model_name='account',
            name='jwt',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_bytes_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
