# Generated by Django 4.2.3 on 2023-07-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_account_last_triggered_alter_account_jwt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login_bytes_code',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
