# Generated by Django 4.2.3 on 2023-07-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_account_login_bytes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login_bytes_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
