# Generated by Django 4.2.3 on 2023-07-09 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_login_bytes_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_time_triggered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
    ]
