# Generated by Django 4.2.3 on 2023-07-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_account_last_time_triggered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_time_triggered',
            field=models.DateTimeField(verbose_name='last time triggered'),
        ),
    ]
