# Generated by Django 4.0.1 on 2022-10-04 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.IntegerField()),
                ('sousCategorie', models.IntegerField()),
                ('titre', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('prix', models.IntegerField()),
                ('livraison', models.BooleanField(default=False)),
                ('ville', models.IntegerField()),
                ('delegation', models.IntegerField()),
                ('principalPhoneNumber', models.BooleanField(default=True)),
                ('secondaryPhoneNumber', models.IntegerField(default=0)),
                ('is_actif', models.BooleanField(default=True)),
                ('times_posted', models.IntegerField(default=0)),
                ('times_deleted', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_created_token', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceDeleteProcess',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annonceToken', models.CharField(max_length=128)),
                ('loggedIn', models.BooleanField(null=True)),
                ('loginPageOnePassed', models.BooleanField(null=True)),
                ('loginPageTwoPassed', models.BooleanField(null=True)),
                ('loginTimeInSeconds', models.FloatField(blank=True, null=True)),
                ('annonceDeleted', models.BooleanField(null=True)),
                ('deleteAnnonceTimeInSeconds', models.FloatField(blank=True, null=True)),
                ('processCompleted', models.BooleanField(default=False)),
                ('started', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='ad_images')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAnnonce', models.BooleanField(null=True)),
                ('deleteAnnonce', models.BooleanField(null=True)),
                ('annonceToDeleteToken', models.CharField(blank=True, max_length=128, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('annonceToCreate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonceOfTask', to='tayara.annonce')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceCreateProcess',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loggedIn', models.BooleanField(null=True)),
                ('loginPageOnePassed', models.BooleanField(null=True)),
                ('loginPageTwoPassed', models.BooleanField(null=True)),
                ('loginTimeInSeconds', models.FloatField(blank=True, null=True)),
                ('newCreatedArticleToken', models.CharField(max_length=128)),
                ('annonceCreated', models.BooleanField(null=True)),
                ('createAnnoncePageOnePassed', models.BooleanField(null=True)),
                ('createAnnoncePageTwoPassed', models.BooleanField(null=True)),
                ('createAnnoncePageThreePassed', models.BooleanField(null=True)),
                ('createAnnoncePageFourPassed', models.BooleanField(null=True)),
                ('createAnnonceTimeInSeconds', models.FloatField(blank=True, null=True)),
                ('processCompleted', models.BooleanField(default=False)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AnnonceOfTheCreateProcess', to='tayara.annonce')),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.AddField(
            model_name='annonce',
            name='images',
            field=models.ManyToManyField(to='tayara.AnnonceImage'),
        ),
    ]
