# Generated by Django 4.2.3 on 2023-07-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.TextField(max_length=24, null=True)),
                ('image', models.ImageField(default=None, upload_to='ad_images')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.TextField(max_length=512)),
                ('main_id', models.TextField(max_length=24, null=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(max_length=512, null=True)),
                ('price', models.IntegerField(null=True)),
                ('is_actif', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(to='tayara.annonceimage')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
