# Generated by Django 4.2.3 on 2023-07-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='hex_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='images',
            field=models.ManyToManyField(blank=True, to='tayara.annonceimage'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='main_id',
            field=models.TextField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
