# Generated by Django 4.2.3 on 2023-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0002_alter_annonce_description_alter_annonce_hex_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonceimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='annonceimage',
            name='main_id',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
