# Generated by Django 4.2.3 on 2023-07-08 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tayara', '0003_remove_annonceimage_image_alter_annonceimage_main_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Annonce_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='main_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
