# Generated by Django 4.2.3 on 2023-07-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0004_annonce_owner_alter_annonce_main_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('LOGIN', 'LOGIN'), ('CREATE', 'CREATE'), ('DELETE', 'DELETE')], max_length=64)),
                ('related_annonce_id', models.CharField(blank=True, max_length=24, null=True)),
                ('jwt', models.CharField(blank=True, max_length=1024, null=True)),
                ('success', models.BooleanField(default=False)),
                ('was_manual', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
