# Generated by Django 4.2.3 on 2023-07-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0006_event_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nature',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('CREATE', 'CREATE'), ('DELETE', 'DELETE')], max_length=10),
        ),
    ]
