# Generated by Django 4.2.3 on 2023-07-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0008_remove_annonce_owner_remove_event_owner_annonce_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='is_onTayaraNow',
            field=models.BooleanField(default=False),
        ),
    ]
