# Generated by Django 4.2.3 on 2023-07-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0010_annonceontayaranow'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonceontayaranow',
            name='tayara_annonce_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
