# Generated by Django 4.2.3 on 2023-07-12 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tayara', '0011_annonceontayaranow_tayara_annonce_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonceontayaranow',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
